<?php

namespace SICLA\HydraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * addressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
}
