parameters:
#    sicla_list.example.class: SICLA\ListBundle\Example

services:
#    sicla_list.example:
#        class: %sicla_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
