<?php

namespace Sidus\SidusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
		
	public function findType ($node){
		$qb = $this->createQueryBuilder('o')
				->leftJoin('o.type','t')
				->addSelect('t');
		
		return $qb->getQuery()->getOneOrNullResult();
	}
}
