<?php

namespace Sidus\SidusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository {

	/**
	 * Find the last version according to the node_id and lang (default:en)
	 * @todo If any version axist according to lang, try the default lang <= Ça ne veut rien dire :D
	 * @param Node $node
	 * @param string $lang
	 * @return Version
	 */
	public function findLastVersion(Node $node, $lang) {
		$qb = $this->createQueryBuilder('v')
				->where('v.node = :node')
				->andwhere('v.lang = :lang')
				->setParameter('node', $node)
				->setParameter('lang', $lang)
				->orderBy('v.revision_date', 'DESC')
				->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();
	}

	/**
	 *
	 * @param Node $node
	 * @param string $lang
	 * @return Version[]
	 */
	public function findAllLastVersions(Node $node) {
		$qb = $this->createQueryBuilder('v')
				->where('v.node = :node')
				->addGroupBy('v.lang')
				->setParameter('node', $node)
				->orderBy('v.revision_date', 'DESC');
		return $qb->getQuery()->getResult();
	}

	public function findByNodeIds(array $node_ids) {
		$qb = $this->getQueryBuilder();
		$qb->where('n.id IN (:node_ids)')->setParameter('node_ids', $node_ids);
		return $qb->getQuery()->getResult();
	}

	public function findByNodeId($node_id) {
		$qb = $this->getQueryBuilder();
		$qb->where('n.id = :node_id')->setParameter('node_id', (int) $node_id);
		return $qb->getQuery()->getResult();
	}

	public function findByParentNode(Node $parent) {
		$qb = $this->getQueryBuilder();
		$qb->where('n.parent = :parent')->setParameter('parent', $parent);
		return $qb->getQuery()->getResult();
	}

	public function findRoots() {
		$qb = $this->getQueryBuilder();
		$qb->where('n.parent IS null');
		return $qb->getQuery()->getResult();
	}

	public function findByNodeName($node_name) {
		$qb = $this->getQueryBuilder();
		$qb->where('n.nodeName = :node_name')->setParameter('node_name', $node_name);
		return $qb->getQuery()->getResult();
	}

	protected function getQueryBuilder() {
		// SELECT n.*, v.*, o.*, t.*
		// FROM version AS v
		// LEFT JOIN node AS n ON v.node_id
		// LEFT JOIN object AS o ON v.object_id
		// LEFT JOIN type AS t ON o.type_id
		// WHERE ...
		// GROUP BY n.id, v.lang
		// ORDER BY n.id, v.revision_date
		$qb = $this->createQueryBuilder('v')
				->join('v.node', 'n')
				->leftJoin('v.object', 'o')
				->leftJoin('o.type', 't')
				->groupBy('n.id')
				->addGroupBy('v.lang')
				->orderBy('n.id', 'ASC')
				->orderBy('v.revisionDate', 'DESC');
		return $qb;
	}

}
