<?php

namespace Sidus\SidusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
	/*
	 * Find the last version according to the id_node and lang (default:en)
	 * @TODO : If any version axist according to lang, try the default lang
	 */
	public function findLastVersion($node, $lang){
		$qb = $this->createQueryBuilder('v');
		$qb	->where('v.node = :node')
			->andwhere('v.lang = :lang')
			->setParameter('node',$node)
			->setParameter('lang',$lang)	
			->orderBy('v.revision_date', 'DESC');
		return $qb->getQuery()->getOneOrNullResult();
	}
}
