<?php

namespace Sidus\SidusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository {

	/**
	 * Find the last version according to the id_node and lang (default:en)
	 * @todo If any version axist according to lang, try the default lang <= Ça ne veut rien dire :D
	 * @param Node $node
	 * @param string $lang
	 * @return Version
	 */
	public function findLastVersion(Node $node, $lang) {
		$qb = $this->createQueryBuilder('v')
				->where('v.node = :node')
				->andwhere('v.lang = :lang')
				->setParameter('node', $node)
				->setParameter('lang', $lang)
				->orderBy('v.revision_date', 'DESC')
				->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();
	}

	/**
	 *
	 * @param Node $node
	 * @param string $lang
	 * @return Version[]
	 */
	public function findAllLastVersions(Node $node) {
		$qb = $this->createQueryBuilder('v')
				->where('v.node = :node')
				->addGroupBy('v.lang')
				->setParameter('node', $node)
				->orderBy('v.revision_date', 'DESC');
		return $qb->getQuery()->getResult();
	}

}
