sidus_sidus:
    resource: "@SidusBundle/Resources/config/routing.yml"
    prefix:   /
    
sicla_hydra:
    resource: "@SICLAHydraBundle/Resources/config/routing.yml"
    prefix:   /hydra

sicla_ara:
    resource: "@SICLAAraBundle/Resources/config/routing.yml"
    prefix:   /ara
# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
