services:
    sidus.menu_builder:
        class: Sidus\SidusBundle\Navbar\MenuBuilder
        arguments: ["@knp_menu.factory"]

    sidus.menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sidus.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    sidus.dropdown:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sidus.menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: dropdown } # The alias is what is used to retrieve the menu

    sidus.navbarsubnavmenu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sidus.menu_builder
        factory_method: createNavbarsSubnavMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: mainsubnav } # The alias is what is used to retrieve the menu

    sidus.componentssubnavmenu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: sidus.menu_builder
        factory_method: createComponentsSubnavMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: mainsubnav } # The alias is what is used to retrieve the menu

