
#sidus_homepage:
#  pattern:  /
#  defaults: { _controller: SidusBundle:Default:home }


#sidus_node_lang:
#  pattern:  /{_locale}/{node_id}
#  defaults: { _controller: SidusBundle:Default:show, node_id:1 }
#  requirements:
#    node_id: \d*
#    _locale: ([a-zA-Z]{2})

login:
  pattern: /login
  defaults: { _controller: SidusBundle:Default:login}
login_check:
  pattern: /login_check
logout:
  pattern: /logout

sidus_show_node:
  pattern:  /{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:show, _locale: ~ }
  requirements:
    node_id: \d*
    _locale: ^[a-z]{2}$

sidus_edit_node:
  pattern:  /edit/{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:edit, _locale: ~ }
  requirements:
    node_id: \d*
    _locale: ^[a-z]{2}$

sidus_choose_node:
  pattern:  /choose/{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:choose, _locale: ~ }
  requirements:
    node_id: \d*
    _locale: ^[a-z]{2}$

sidus_add_node:
  pattern:  /add/{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:add, _locale: ~ }
  requirements:
    node_id: \d*
    _locale: ^[a-z]{2}$

#@TODO si l'id de la node n'est pas donné -> erreur -> node_id ne s'initialise pas a 1. Problème temporairement réglé alarache dans le controller

#sidus_user:
#  pattern: /users/{id}
#  defaults: { _controller: SidusBundle:User:form }
#  requirements:
#    id: \d*
#
#SidusBundle_user:
#  resource: "@SidusBundle/Resources/config/routing/user.yml"
#  prefix:   /user