
#sidus_homepage:
#  pattern:  /
#  defaults: { _controller: SidusBundle:Default:home }


#sidus_node_lang:
#  pattern:  /{_locale}/{id_node}
#  defaults: { _controller: SidusBundle:Default:view, id_node:1 }
#  requirements:
#    id_node: \d*
#    _locale: ([a-zA-Z]{2})

login:
  pattern: /login
  defaults: { _controller: SidusBundle:Default:login}
login_check:
  pattern: /login_check
logout:
  pattern: /logout
    
sidus_view_node:
  pattern:  /{_locale}/{id_node}
  defaults: { _controller: SidusBundle:Default:view}
  requirements:
    id_node: \d*
    _locale: ^[a-z]{2}$
    
sidus_edit_node:
  pattern:  /{_locale}/{id_node}/edit
  defaults: { _controller: SidusBundle:Default:edit}
  requirements:
    id_node: \d*
    _locale: ^[a-z]{2}$

sidus_choose_node:
  pattern:  /{_locale}/{id_node}/choose
  defaults: { _controller: SidusBundle:Default:choose}
  requirements:
    id_node: \d*
    _locale: ^[a-z]{2}$
    
sidus_add_node:
  pattern:  /{_locale}/{id_node}/add
  defaults: { _controller: SidusBundle:Default:add}
  requirements:
    id_node: \d*
    _locale: ^[a-z]{2}$
#@TODO si l'id de la node n'est pas donné -> erreur -> id_node ne s'initialise pas a 1. Problème temporairement réglé alarache dans le controller 

#sidus_user:
#  pattern: /users/{id}
#  defaults: { _controller: SidusBundle:User:form }
#  requirements:
#    id: \d*
#    
#SidusBundle_user:
#  resource: "@SidusBundle/Resources/config/routing/user.yml"
#  prefix:   /user