
sidus_homepage:
  pattern:  /
  defaults: { _controller: SidusBundle:Default:home }

sidus_node:
  pattern:  /{node}
  defaults: { _controller: SidusBundle:Default:view, node:1 }
  requirements:
    node: ^(\d+|[A-Za-z0-9-_]+)$