
#sidus_homepage:
#  pattern:  /
#  defaults: { _controller: SidusBundle:Default:home }


#sidus_node_lang:
#  pattern:  /{_locale}/{node_id}
#  defaults: { _controller: SidusBundle:Default:show, node_id:1 }
#  requirements:
#    node_id: \d*
#    _locale: ([a-zA-Z]{2})

login:
  pattern: /login
  defaults: { _controller: SidusBundle:Default:login}
login_check:
  pattern: /login_check
logout:
  pattern: /logout

sidus_show_node:
  pattern:  /{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:show, node_id: home, _locale: ~ }
  requirements:
    _locale: ^[a-z]{2}$

sidus_edit_node:
  pattern:  /edit/{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:edit, _locale: ~ }
  requirements:
    _locale: ^[a-z]{2}$

sidus_choose_node:
  pattern:  /choose/{node_id}/{_locale}
  defaults: { _controller: SidusBundle:Default:choose, _locale: ~ }
  requirements:
    _locale: ^[a-z]{2}$

sidus_delete_node:
  pattern:  /delete/{node_id}
  defaults: { _controller: SidusBundle:Default:delete }

sidus_move_node:
  pattern:  /move/{node_id}
  defaults: { _controller: SidusBundle:Default:move }

sidus_link_node:
  pattern:  /link/{node_id}
  defaults: { _controller: SidusBundle:Default:link }

sidus_copy_node:
  pattern:  /copy/{node_id}
  defaults: { _controller: SidusBundle:Default:copy }

sidus_node_permissions:
  pattern:  /permissions/{node_id}
  defaults: { _controller: SidusBundle:Default:permissions }

sidus_node_history:
  pattern:  /history/{node_id}
  defaults: { _controller: SidusBundle:Default:history }

sidus_node_feed:
  pattern:  /feed/{node_id}
  defaults: { _controller: SidusBundle:Default:feed }

sidus_favorite_node:
  pattern:  /favorite/{node_id}
  defaults: { _controller: SidusBundle:Default:favorite }

sidus_print_node:
  pattern:  /print/{node_id}
  defaults: { _controller: SidusBundle:Default:print }

sidus_localize_node:
  pattern:  /localize/{node_id}
  defaults: { _controller: SidusBundle:Default:localize }

#sidus_user:
#  pattern: /users/{id}
#  defaults: { _controller: SidusBundle:User:form }
#  requirements:
#    id: \d*
#
#SidusBundle_user:
#  resource: "@SidusBundle/Resources/config/routing/user.yml"
#  prefix:   /user