parameters:
#    sidus_sidus.example.class: Sidus\SidusBundle\Example

services:
#    sidus_sidus.example:
#        class: %sidus_sidus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
