parameters:
#    sidus_admin.example.class: Sidus\AdminBundle\Example

services:
#    sidus_admin.example:
#        class: %sidus_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
