sicla_list_ara:
    resource: "@SICLAAraBundle/Resources/config/lists/routing.yml"
    prefix:   /list

sicla_ara_validate:
  pattern:  /validate/{node_id}/{lang}
  defaults: { _controller: SICLAAraBundle:Annonce:validate, lang: ~ }
  requirements:
    lang: ^[a-z]{2}$
    
sicla_ara_archivate:
  pattern:  /archivate/{node_id}/{lang}
  defaults: { _controller: SICLAAraBundle:Annonce:archivate, lang: ~ }
  requirements:
    lang: ^[a-z]{2}$   
    
sicla_ara_contact:
  pattern:  /contact/{node_id}/{lang}
  defaults: { _controller: SICLAAraBundle:Annonce:contact, lang: ~ }
  requirements:
    lang: ^[a-z]{2}$    