<?php

namespace SICLA\AraBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * AffectationDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationDemandeRepository extends EntityRepository
{
	
}
