<?php

namespace SICLA\AraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnimalRepository extends EntityRepository
{
}
